name: Build & Test #Name of the workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Node JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run the API and Postman's tests
        run: |
          cd ./candidate-technical-assessment-sdet-exercise &&
          mvn clean package &&
          docker build --tag gaggle-image . &&
          docker run --publish 8080:8080 gaggle-image &
          sleep 80
          cd ./candidate-technical-assessment-sdet-exercise && ./node_modules/newman/bin/newman.js run gaggleAssessment.postman_collection.json

        env:
          API_HOST: 0.0.0.0
          DB_HOST: localhost
          CI: true
